// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using babe_algorithms.Models;
using babe_algorithms.Services;

namespace babe_algorithms.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211106183837_CartState")]
    partial class CartState
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasPostgresEnum(null, "unit", new[] { "tablespoon", "teaspoon", "milliliter", "cup", "fluid_ounce", "pint", "quart", "gallon", "liter", "count", "ounce", "pound", "milligram", "gram", "kilogram" })
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("CategoryRecipe", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipesId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoriesId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("CategoryRecipe");
                });

            modelBuilder.Entity("babe_algorithms.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("babe_algorithms.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("babe_algorithms.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Data")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("babe_algorithms.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("babe_algorithms.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CaloriesPerServing")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("Cooktime")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ServingsProduced")
                        .HasColumnType("double precision");

                    b.Property<string>("StaticImage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("CategoryRecipe", b =>
                {
                    b.HasOne("babe_algorithms.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("babe_algorithms.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("babe_algorithms.Models.Cart", b =>
                {
                    b.OwnsMany("babe_algorithms.Models.CartIngredient", "IngredientState", b1 =>
                        {
                            b1.Property<Guid>("CartId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<bool>("Checked")
                                .HasColumnType("boolean");

                            b1.Property<Guid?>("IngredientId")
                                .HasColumnType("uuid");

                            b1.HasKey("CartId", "Id");

                            b1.HasIndex("IngredientId");

                            b1.ToTable("CartIngredient");

                            b1.WithOwner()
                                .HasForeignKey("CartId");

                            b1.HasOne("babe_algorithms.Models.Ingredient", "Ingredient")
                                .WithMany()
                                .HasForeignKey("IngredientId");

                            b1.Navigation("Ingredient");
                        });

                    b.OwnsMany("babe_algorithms.Models.RecipeRequirement", "RecipeRequirement", b1 =>
                        {
                            b1.Property<Guid>("CartId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<double>("Quantity")
                                .HasColumnType("double precision");

                            b1.Property<Guid?>("RecipeId")
                                .HasColumnType("uuid");

                            b1.HasKey("CartId", "Id");

                            b1.HasIndex("RecipeId");

                            b1.ToTable("RecipeRequirement");

                            b1.WithOwner()
                                .HasForeignKey("CartId");

                            b1.HasOne("babe_algorithms.Recipe", "Recipe")
                                .WithMany()
                                .HasForeignKey("RecipeId");

                            b1.Navigation("Recipe");
                        });

                    b.Navigation("IngredientState");

                    b.Navigation("RecipeRequirement");
                });

            modelBuilder.Entity("babe_algorithms.Models.Image", b =>
                {
                    b.HasOne("babe_algorithms.Recipe", null)
                        .WithMany("Images")
                        .HasForeignKey("RecipeId");
                });

            modelBuilder.Entity("babe_algorithms.Recipe", b =>
                {
                    b.OwnsMany("babe_algorithms.IngredientRequirement", "Ingredients", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("IngredientId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Quantity")
                                .HasColumnType("double precision");

                            b1.Property<Unit>("Unit")
                                .HasColumnType("unit");

                            b1.HasKey("RecipeId", "Id");

                            b1.HasIndex("IngredientId");

                            b1.ToTable("IngredientRequirement");

                            b1.HasOne("babe_algorithms.Models.Ingredient", "Ingredient")
                                .WithMany()
                                .HasForeignKey("IngredientId");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");

                            b1.Navigation("Ingredient");
                        });

                    b.OwnsMany("babe_algorithms.RecipeStep", "Steps", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<string>("Text")
                                .HasColumnType("text");

                            b1.HasKey("RecipeId", "Id");

                            b1.ToTable("RecipeStep");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.Navigation("Ingredients");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("babe_algorithms.Recipe", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
