// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using babe_algorithms.Models;
using babe_algorithms.Services;

#nullable disable

namespace babe_algorithms.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220407032210_CategoryToMultipartRecipeRelation")]
    partial class CategoryToMultipartRecipeRelation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "unit", new[] { "tablespoon", "teaspoon", "milliliter", "cup", "fluid_ounce", "pint", "quart", "gallon", "liter", "count", "ounce", "pound", "milligram", "gram", "kilogram" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("babe_algorithms.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("babe_algorithms.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("babe_algorithms.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Data")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MultiPartRecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MultiPartRecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("babe_algorithms.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NutritionDataNdbNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NutritionDataNdbNumber");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("babe_algorithms.Models.MultiPartRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CaloriesPerServing")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("Cooktime")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Name" });

                    b.Property<double>("ServingsProduced")
                        .HasColumnType("double precision");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("StaticImage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("MultiPartRecipes");
                });

            modelBuilder.Entity("babe_algorithms.Models.RecipeComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MultiPartRecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MultiPartRecipeId");

                    b.ToTable("RecipeComponent");
                });

            modelBuilder.Entity("babe_algorithms.Models.StandardReferenceNutritionData", b =>
                {
                    b.Property<int>("NdbNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NdbNumber"));

                    b.Property<string>("CountRegex")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FdcId")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("FoodCategory")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("FoodNutrients")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("FoodPortions")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("NutrientConversionFactors")
                        .HasColumnType("jsonb");

                    b.HasKey("NdbNumber");

                    b.ToTable("SRNutritionData");
                });

            modelBuilder.Entity("babe_algorithms.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CaloriesPerServing")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("Cooktime")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ServingsProduced")
                        .HasColumnType("double precision");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("StaticImage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("CategoryMultiPartRecipe", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MultiPartRecipesId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoriesId", "MultiPartRecipesId");

                    b.HasIndex("MultiPartRecipesId");

                    b.ToTable("CategoryMultiPartRecipe");
                });

            modelBuilder.Entity("CategoryRecipe", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipesId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoriesId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("CategoryRecipe");
                });

            modelBuilder.Entity("babe_algorithms.Models.Cart", b =>
                {
                    b.OwnsMany("babe_algorithms.Models.CartIngredient", "IngredientState", b1 =>
                        {
                            b1.Property<Guid>("CartId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<bool>("Checked")
                                .HasColumnType("boolean");

                            b1.Property<Guid?>("IngredientId")
                                .HasColumnType("uuid");

                            b1.HasKey("CartId", "Id");

                            b1.HasIndex("IngredientId");

                            b1.ToTable("CartIngredient");

                            b1.WithOwner()
                                .HasForeignKey("CartId");

                            b1.HasOne("babe_algorithms.Models.Ingredient", "Ingredient")
                                .WithMany()
                                .HasForeignKey("IngredientId");

                            b1.Navigation("Ingredient");
                        });

                    b.OwnsMany("babe_algorithms.Models.RecipeRequirement", "RecipeRequirement", b1 =>
                        {
                            b1.Property<Guid>("CartId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("MultiPartRecipeId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Quantity")
                                .HasColumnType("double precision");

                            b1.Property<Guid?>("RecipeId")
                                .HasColumnType("uuid");

                            b1.HasKey("CartId", "Id");

                            b1.HasIndex("MultiPartRecipeId");

                            b1.HasIndex("RecipeId");

                            b1.ToTable("RecipeRequirement");

                            b1.WithOwner()
                                .HasForeignKey("CartId");

                            b1.HasOne("babe_algorithms.Models.MultiPartRecipe", "MultiPartRecipe")
                                .WithMany()
                                .HasForeignKey("MultiPartRecipeId");

                            b1.HasOne("babe_algorithms.Recipe", "Recipe")
                                .WithMany()
                                .HasForeignKey("RecipeId");

                            b1.Navigation("MultiPartRecipe");

                            b1.Navigation("Recipe");
                        });

                    b.Navigation("IngredientState");

                    b.Navigation("RecipeRequirement");
                });

            modelBuilder.Entity("babe_algorithms.Models.Image", b =>
                {
                    b.HasOne("babe_algorithms.Models.MultiPartRecipe", null)
                        .WithMany("Images")
                        .HasForeignKey("MultiPartRecipeId");

                    b.HasOne("babe_algorithms.Recipe", null)
                        .WithMany("Images")
                        .HasForeignKey("RecipeId");
                });

            modelBuilder.Entity("babe_algorithms.Models.Ingredient", b =>
                {
                    b.HasOne("babe_algorithms.Models.StandardReferenceNutritionData", "NutritionData")
                        .WithMany()
                        .HasForeignKey("NutritionDataNdbNumber");

                    b.Navigation("NutritionData");
                });

            modelBuilder.Entity("babe_algorithms.Models.RecipeComponent", b =>
                {
                    b.HasOne("babe_algorithms.Models.MultiPartRecipe", null)
                        .WithMany("RecipeComponents")
                        .HasForeignKey("MultiPartRecipeId");

                    b.OwnsMany("babe_algorithms.Models.MultiPartIngredientRequirement", "Ingredients", b1 =>
                        {
                            b1.Property<Guid>("RecipeComponentId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("IngredientId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Position")
                                .HasColumnType("integer");

                            b1.Property<double>("Quantity")
                                .HasColumnType("double precision");

                            b1.Property<Unit>("Unit")
                                .HasColumnType("unit");

                            b1.HasKey("RecipeComponentId", "Id");

                            b1.HasIndex("IngredientId");

                            b1.ToTable("MultiPartIngredientRequirement");

                            b1.HasOne("babe_algorithms.Models.Ingredient", "Ingredient")
                                .WithMany()
                                .HasForeignKey("IngredientId");

                            b1.WithOwner()
                                .HasForeignKey("RecipeComponentId");

                            b1.Navigation("Ingredient");
                        });

                    b.OwnsMany("babe_algorithms.Models.MultiPartRecipeStep", "Steps", b1 =>
                        {
                            b1.Property<Guid>("RecipeComponentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Text")
                                .HasColumnType("text");

                            b1.HasKey("RecipeComponentId", "Id");

                            b1.ToTable("MultiPartRecipeStep");

                            b1.WithOwner()
                                .HasForeignKey("RecipeComponentId");
                        });

                    b.Navigation("Ingredients");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("babe_algorithms.Recipe", b =>
                {
                    b.OwnsMany("babe_algorithms.IngredientRequirement", "Ingredients", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("IngredientId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Position")
                                .HasColumnType("integer");

                            b1.Property<double>("Quantity")
                                .HasColumnType("double precision");

                            b1.Property<Unit>("Unit")
                                .HasColumnType("unit");

                            b1.HasKey("RecipeId", "Id");

                            b1.HasIndex("IngredientId");

                            b1.ToTable("IngredientRequirement");

                            b1.HasOne("babe_algorithms.Models.Ingredient", "Ingredient")
                                .WithMany()
                                .HasForeignKey("IngredientId");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");

                            b1.Navigation("Ingredient");
                        });

                    b.OwnsMany("babe_algorithms.RecipeStep", "Steps", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Text")
                                .HasColumnType("text");

                            b1.HasKey("RecipeId", "Id");

                            b1.ToTable("RecipeStep");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.Navigation("Ingredients");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("CategoryMultiPartRecipe", b =>
                {
                    b.HasOne("babe_algorithms.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("babe_algorithms.Models.MultiPartRecipe", null)
                        .WithMany()
                        .HasForeignKey("MultiPartRecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoryRecipe", b =>
                {
                    b.HasOne("babe_algorithms.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("babe_algorithms.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("babe_algorithms.Models.MultiPartRecipe", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("RecipeComponents");
                });

            modelBuilder.Entity("babe_algorithms.Recipe", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
